global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '<sender>@gmail.com'
  smtp_auth_username: 'username'
  smtp_auth_password: 'password'
  smtp_require_tls: true

receivers:
  - name: email-alerts
    email_configs:
      - to: '<receiver>@gmail.com'

route:
  group_by: ['cpu-alert']
  receiver: email-alerts
